name: 'Synopsys Detect'
description: 'Add SAST and SCA scanning to your GitHub repositories with Synopsys Coverity on Polaris and Black Duck.'
author: 'Gautam Baghel @ Synopsys'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  blackduck.url:
    description: 'Black Duck server url'
    required: true
  blackduck.api.token:
    description: 'Black Duck API token'
    required: true
  args:
    description: 'Synopsys Detect arguments'
    required: false
  version:
    description: 'Synopsys Detect version'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
